---
# Resource Quotas para ambiente de homologação/staging
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hlm-resource-quota
  namespace: hlm
  labels:
    environment: hlm
    app.kubernetes.io/managed-by: argocd
spec:
  hard:
    # Compute resources (entre dev e prod)
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    
    # Storage
    requests.storage: 500Gi
    persistentvolumeclaims: "25"
    
    # Objects
    count/configmaps: "100"
    count/secrets: "100"
    count/services: "50"
    count/deployments.apps: "30"
    
    # Crossplane Claims
    count/databases.platform.example.com: "10"
    count/buckets.platform.example.com: "20"
    count/networks.platform.example.com: "3"

